Footer
germankern/Face-It pull request #21
Opened 2023-03-02 07:38 UTC by JoseAdvinculaFullStack

Habilite el footer para que este siempre abajo de la pantalla y que todas las rutas puedan  tener el layout y de esta manera reutilizar componentes

2023-03-02 07:42 UTC, JoseAdvinculaFullStack commented
![image](https://user-images.githubusercontent.com/115754861/222362644-eef36adc-79c0-4c82-af9f-db973e3e1fbe.png)
Footer Desktop
![image](https://user-images.githubusercontent.com/115754861/222363029-6597867e-ca87-43f4-ae85-340973278e24.png)
Footer Mobile

2023-03-02 14:31 UTC, adrianponce89 requested changes

2023-03-02 14:31 UTC, adrianponce89 commented on src/components/Copyright/index.jsx
> +      <Brand
`<Brand type="Copyright" />`

2023-03-02 14:31 UTC, adrianponce89 commented on src/components/Brand/styles.module.css
> +}
Agrega copyrightContainer a estos estilos 
```
.containerBrand: {
  display: flex;
  alignItems: center;
}

.copyrightContainer {
  width: 100%;
  height: 50px;
  marginRight: 20px;
  justifyContent: end;
}

@media (min-width: 768px) {
  .containerBrand {
    margin-left: 25px;
  }
}   
```

2023-03-02 14:31 UTC, adrianponce89 commented on src/components/Brand/index.jsx
>      >
Intenta no usar estilos en linea
```
const Brand = ({type}) => {
  return (
    <div className={[styles.containerBrand, type === 'Copyright' && styles.copyrightContainer]}>
```

2023-03-02 14:31 UTC, adrianponce89 commented on src/pages/survey/index.jsx
> +    return(
Este archivo esta de mas, no parece que lo estes usando en ninguna parte. Si no tiene uso borralo por favor

2023-03-05 14:04 UTC, adrianponce89 requested changes

2023-03-05 14:04 UTC, adrianponce89 commented on src/components/Brand/index.jsx
> +  console.log(props.type === "Copyright");
Borra este console log

2023-03-05 14:04 UTC, adrianponce89 commented on src/styles/globals.css
>  }
De que es este css? Tene cuidado porque los nombres de las clases varian por cada vez que se inicia la aplicacion. Asi que si usaste `styles_container__vxHJV` por algo que se genero, ya no va a existir.
Borra esta parte

2023-03-05 15:22 UTC, adrianponce89 approved these changes

2023-03-05 15:29 UTC, merged