Politicas
germankern/Face-It pull request #28
Opened 2023-03-06 21:31 UTC by JoseAdvinculaFullStack

Termine de realizar la seccion de politcas de la pages de politicas y privacidad tanto en mobile como desktop

2023-03-06 21:34 UTC, JoseAdvinculaFullStack commented
![image](https://user-images.githubusercontent.com/115754861/223235561-a61bfc55-19e7-412d-98b5-f28b96932095.png)
![image](https://user-images.githubusercontent.com/115754861/223235667-c565d756-78d5-438a-9161-56e87c24785f.png)

2023-03-07 15:26 UTC, adrianponce89 requested changes

2023-03-07 15:26 UTC, adrianponce89 commented on src/pages/politicas/index.jsx
> +
Agrega esto a un archivos strings.js en la misma carpeta e importalo

2023-03-07 15:26 UTC, adrianponce89 commented on src/components/TextSection/index.jsx
> +export default TextSection;
Para simplificar podrias hacer:
```
import Cokkies from "../Cokkies/index";
import Licencia from "../Licencia/index";
import Hipervinculos from "../Hipervinculos/index";
import Responsabilidad from "../Responsabilidad/index";
import Reserva from "../Reserva/index";
import Derechos from "../Derechos";
import SectionParagraphPoliticals from "../SectionParagraphPoliticals";

const getComponent = (type) =>
  type === "Cokkies"
    ? Cokkies
    : type === "Licencia"
    ? Licencia
    : type === "Hipervinculos"
    ? Hipervinculos
    : type === "Responsabilidad"
    ? Responsabilidad
    : type === "Reserva"
    ? Reserva
    : type === "Derechos"
    ? Derechos
    : SectionParagraphPoliticals;

const TextSection = ({
  type,
  title,
  id,
  allParagraph,
  allParagraph2,
  allParagraph3,
  allParagraph4,
  allList,
  allList2,
  allList3,
}) => {
  let textSection;
  allParagraph = Object.values(allParagraph);
  allParagraph2 = allParagraph2 && Object.values(allParagraph2);
  allParagraph3 = allParagraph3 && Object.values(allParagraph3);
  allParagraph4 = allParagraph4 && Object.values(allParagraph4);
  allList = allList && Object.values(allList);
  allList2 = allList2 && Object.values(allList2);
  allList3 = allList3 && Object.values(allList3);

  const Component = getComponent(type);

  if (Component) {
    textSection = (
      <Component
        title={title}
        allParagraph={allParagraph}
        allParagraph2={allParagraph2}
        allParagraph3={allParagraph3}
        allParagraph4={allParagraph4}
        allList={allList}
        allList2={allList2}
        allList3={allList3}
        id={id}
      />
    );
  }

  return <>{textSection}</>;
};

export default TextSection;

```

2023-03-07 15:26 UTC, adrianponce89 commented on src/components/TextSection/index.jsx
> +export default TextSection;
Aunque lo mejor seria evitar usar TextSection y usar el correspondiente component en cada parte. Todo el componente TextSection parece estar de mas

2023-03-07 15:26 UTC, adrianponce89 commented on src/pages/politicas/index.jsx
> +
a cada uno de estos agregale el type correspondiente:
Cokkies, Licencia, Hipervinculos, Responsabilidad, Reserva, Derechos, SectionParagraphPoliticals

2023-03-07 15:26 UTC, adrianponce89 commented on src/pages/politicas/index.jsx
> +            />
```
<TextSection
              key={key}
              type={section.type}
              id={section.id}
              title={section.title}
              allParagraph={section.allParagraph}
              allParagraph2={section.allParagraph2}
              allList={section.allList}
            />
```

2023-03-07 15:26 UTC, adrianponce89 commented on src/pages/terms/index.jsx
> +            />
Agregale el type

2023-03-13 17:41 UTC, adrianponce89 approved these changes
Modifica el error de escritura (typo ==. typography error)

2023-03-13 17:41 UTC, adrianponce89 commented on src/pages/terms/string.js
>      title: "Cokkies:",
Se escribe Cookies

2023-03-16 19:54 UTC, merged